import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-context-help',
  templateUrl: './context-help.component.html',
  styleUrls: ['./context-help.component.css']
})
export class ContextHelpComponent implements OnInit {

  @Input() pageName: string;
  display: boolean = false;

  addUser: boolean = false;
  signIn: boolean = false;
  signInDetails: boolean = false;
  signOut: boolean = false;
  signOutDetails: boolean = false;
  createInvoice: boolean = false;
  createInvoiceDetails: boolean = false;
  enrollFamily: boolean = false;
  familyDetailsAdmin: boolean = false;
  familyDetailsRegular: boolean = false;
  familyListAdmin: boolean = false;
  familyListRegular: boolean = false;
  invoiceDetails: boolean = false;
  invoiceList: boolean = false;
  invoices: boolean = false;
  manageRates: boolean = false;
  resetPassword: boolean = false;
  userList: boolean = false;
  userProfile: boolean = false;
  inactiveFamilyList: boolean = false;
  inactiveFamilyDetails: boolean = false;
  unknown: boolean = false;

  constructor() {
  }

  ngOnInit() {
    switch (this.pageName) {
      case 'add-user':
        this.addUser = true;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'sign-in':
        this.addUser = false;
        this.signIn = true;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'sign-in-details':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = true;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'sign-out':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = true;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'sign-out-details':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = true;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'create-invoice':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = true;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'create-invoice-details':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = true;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'enroll-family':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = true;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'family-details-admin':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = true;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'family-details-regular':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = true;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'family-list-admin':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = true;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'family-list-regular':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = true;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'invoice-details':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = true;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'invoice-list':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = true;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'invoices':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = true;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'manage-rates':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = true;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'reset-password':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = true;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'user-list':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = true;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'user-profile':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = true;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'inactive-family-list':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = true;
        this.inactiveFamilyDetails = false;
        this.unknown = false;
        break;
      case 'inactive-family-details':
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = true;
        this.unknown = false;
        break;
      default:
        this.addUser = false;
        this.signIn = false;
        this.signInDetails = false;
        this.signOut = false;
        this.signOutDetails = false;
        this.createInvoice = false;
        this.createInvoiceDetails = false;
        this.enrollFamily = false;
        this.familyDetailsAdmin = false;
        this.familyDetailsRegular = false;
        this.familyListAdmin = false;
        this.familyListRegular = false;
        this.invoiceDetails = false;
        this.invoiceList = false;
        this.invoices = false;
        this.manageRates = false;
        this.resetPassword = false;
        this.userList = false;
        this.userProfile = false;
        this.inactiveFamilyList = false;
        this.inactiveFamilyDetails = false;
        this.unknown = true;
    }
  }
}
